### ISSUE TITLE
Onde adicionar exercícios? Labs são novos posts?

### ISSUE THREAD

**Issue by jtrecenti** [curso-r/verao2016#3]
1. exercicios
   a. adicionar como aba, substituindo Projects
   b. adicionar como post, com uma categoria "exercício". O template filtra de um jeito bem legal, talvez seja bom aproveitar
2. Labs ficam dentro da aula ou como post novo?

**Comment by dfalbel** [comment]
Estou meio sem idéia disso! Como acham melhor?
Eu pensei em fazer uma nova aba de exercícios com o mesmo layout da página das aulas. O que acham?

Os labs podem ficar como aulas né? Afinal eles são feitos durante a aula certo?

**Comment by dfalbel** [comment]
desse jeito basta colcoar a tag exercicio nos Rmd de exercicios
