### ISSUE TITLE
Fazer o mathjax funcionar

### ISSUE THREAD

**Issue by jtrecenti** [curso-r/verao2016#6]
Achei isso

http://jekyllrb.com/docs/extras/

e isso 

http://gastonsanchez.com/opinion/2014/02/16/Mathjax-with-jekyll/

mas ainda nao consegui

**Comment by dfalbel** [comment]
Já deve estar funcionando pelo que você fez! Acho que só precisa mudar uma configuração p/ ele entender o inline.

Em qual post tem MathJax?

**Comment by dfalbel** [comment]
@jtrecenti Tá arrumado! Pra fazer inline precisa usar assim \( expressao latex \)
O padrão é esse por que aparece dinheiro e muitas frases.
Pode ser assim? Ou prefere mudar p/ o padrão $ expressao $?
